# Generated by Django 4.1.3 on 2025-01-10 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simplybooksapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='author_id',
            new_name='author',
        ),
    ]
